name: "Collect IPs"

on:
  push:
    branches: [ "main" ]
  schedule:
   - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install dnspython requests
      - name: Resolve domains, collect and store IP addresses
        run: |
          python collect.py
          python cf2dns.py
          python mergeList.py
          git config --global user.email "RododoIsHereAction@proton.me"
          git config --global user.name "RododoIsHere"
          git add -A
          git commit -m "Automatic IP sync $(TZ='Asia/Tehran' date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push
