name: "Collect IPs"

on:
  # push:
  #   branches: [ "main" ]
  schedule:
   - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Resolve domains, collect and store IP addresses
        run: |
          python -m pip install dnspython
          python collect.py
          git config --global user.email "RododoIsHereAction@proton.me"
          git config --global user.name "RododoIsHere"
          git add -A
          git commit -m "Automatic update"
          git push
